### ISSUE TITLE
Suggestion: automatically 0-pad numeric arguments

### ISSUE THREAD

**Issue by Kodiologist** [USEPA/RAQSAPI#6]
As things stand, for example, if you provide `stateFIPS = 1` to `aqs_sampledata_by_site`, you get the error `state: 1, requires 2 digit numeric value`. You're expected to indicate state 1 as `"01"` instead.

It would likely be better for the API itself to accept unpadded values, but if the API is going to remain picky about this, the package can work around it.

**Comment by Kodiologist** [comment]
More dangerously, it appears that if `sitenum` isn't 0-padded, there's no error message; you just don't get any data, because the API can't find any such site.

**Comment by mccroweyclinton-EPA** [comment]
Thank you, I will look into this.

**Comment by mccroweyclinton-EPA** [comment]
Instead of padding variables it has been decided that a check should be added that validates parameters and throws an error if the format or class of the variable is incorrect. This is addressed in [commit fd587cc](https://github.com/USEPA/RAQSAPI/commit/fd587ccc32da334398e2d13a45ed299f811856bc).

**Comment by Kodiologist** [comment]
Thanks. I see in the same commit that you say that failing to 0-pad "may lead to unexpected results". Did you write that before you added the code to check for it?

**Comment by mccroweyclinton-EPA** [comment]
I saw that shortly after I pushed the code up. That failure is from the github actions. If you look at the actions tabs for this repository you can see that the failure is due to pandoc not being installed in the automated build environment that github provides, so it is unable to correctly build the documentation. I am not sure why it's not working now as I have not manually made any substantial changes to the documentation. The code should work though, and the documentation built fine on my local machine. I will look into this over the next few days. My guess is that there has been an update to either pandoc or github actions that will require a change to make the two work together in the future.
